name: build

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3

      - name: Using latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'

      - name: Setup libcwebp for image conversions
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebp-dev webp

      - name: Clean install node dependcies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm run test
