name: ci

on:
  workflow_dispatch:
  pull_request:
    branches: "main"
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ "16", "18", "latest" ]
    name: Building with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Clean install dependencies
        run: npm ci

      - name: Test build
        run: npm run build --if-present
