name: Deploy to GH Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Using latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          
      - name: Clean install node dependcies
        run: npm ci
        
      - name: Build
        run: npm run build --if-present
    
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Using latest Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
          
      - name: Clean install node dependcies
        run: npm ci
        
      - name: Build
        run: npm run build --if-present
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
